import { readFileSync } from 'fs';
const code = readFileSync('src/routes/index.jsx', 'utf8');
console.log('Length:', code.length);
console.log('Has Route:', code.includes('export const Route'));
console.log('Has HomePage:', code.includes('function HomePage'));
console.log('Has CaptionPlayer:', code.includes('CaptionPlayer'));
console.log('Has pricing link:', code.includes('/pricing'));
console.log('Has signup link:', code.includes('/signup'));
console.log('Has login link:', code.includes('/login'));
console.log('Has Dashboard:', code.includes('Dashboard'));
console.log('Has privacy link:', code.includes('/privacy'));
console.log('Has terms link:', code.includes('/terms'));
console.log('Has changelog link:', code.includes('/changelog'));
console.log('Has templates link:', code.includes('/templates'));
console.log('Has about link:', code.includes('/about'));
console.log('Has plugin link:', code.includes('/plugin/download'));
console.log('Has Particles component:', code.includes('function Particles'));
console.log('Has useScrollDirection:', code.includes('function useScrollDirection'));
console.log('Has useInView:', code.includes('function useInView'));
console.log('Has StatCard:', code.includes('function StatCard'));
console.log('Has FeatureCard:', code.includes('function FeatureCard'));
