export const PRESETS = [
  {
    id: "beast",
    name: "Beast Style",
    font: "Inter, system-ui, sans-serif",
    color: "#facc15",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 2px 8px rgba(0,0,0,0.5)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "karaoke",
    name: "Karaoke Smooth",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "#facc15",
    bg: "rgba(0,0,0,0.35)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 800,
    italic: false,
  },
  {
    id: "minimal-bold",
    name: "Minimal Bold",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.6)",
    shadow: "0 1px 4px rgba(0,0,0,0.3)",
    letterSpacing: "0.04em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "hype-amber",
    name: "Hype Amber",
    font: "Inter, system-ui, sans-serif",
    color: "#09090b",
    stroke: "transparent",
    bg: "#facc15",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "clean-mono",
    name: "Clean Mono",
    font: "'JetBrains Mono', monospace",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(24,24,27,0.85)",
    shadow: "none",
    letterSpacing: "0",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "hormozi",
    name: "Hormozi",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "#000000",
    bg: "#111111",
    shadow: "0 2px 12px rgba(0,0,0,0.6)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "grit",
    name: "Grit",
    font: "Inter, system-ui, sans-serif",
    color: "#facc15",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(250,204,21,0.15)",
    letterSpacing: "0.06em",
    case: "uppercase",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "prism",
    name: "Prism",
    font: "Inter, system-ui, sans-serif",
    color: "#a78bfa",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(167,139,250,0.15)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "slide",
    weight: 800,
    italic: false,
  },
  {
    id: "glitch",
    name: "Glitch",
    font: "Inter, system-ui, sans-serif",
    color: "#22d3ee",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(34,211,238,0.2)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "word-pop",
    name: "Word Pop",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.5)",
    shadow: "none",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "bubble",
    name: "Bubble",
    font: "Inter, system-ui, sans-serif",
    color: "#000000",
    stroke: "transparent",
    bg: "#facc15",
    shadow: "0 4px 12px rgba(250,204,21,0.3)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "deep-glow",
    name: "Deep Glow",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "rgba(250,204,21,0.6)",
    bg: "transparent",
    shadow: "0 0 30px rgba(250,204,21,0.25)",
    letterSpacing: "0.04em",
    case: "none",
    animation: "fade",
    weight: 800,
    italic: false,
  },
  {
    id: "highlighted",
    name: "Highlighted",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "#000000",
    bg: "rgba(250,204,21,0.2)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 700,
    italic: false,
  },
  {
    id: "liquid-glass",
    name: "Liquid Glass",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(255,255,255,0.08)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "delhi",
    name: "Delhi",
    font: "Inter, system-ui, sans-serif",
    color: "#facc15",
    stroke: "#000000",
    bg: "transparent",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "neon-cyan",
    name: "Neon Cyan",
    font: "Inter, system-ui, sans-serif",
    color: "#06b6d4",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 25px rgba(6,182,212,0.3)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "neon-pink",
    name: "Neon Pink",
    font: "Inter, system-ui, sans-serif",
    color: "#ec4899",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 25px rgba(236,72,153,0.3)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    font: "'Courier New', monospace",
    color: "#facc15",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.7)",
    shadow: "0 0 15px rgba(250,204,21,0.2)",
    letterSpacing: "0.08em",
    case: "uppercase",
    animation: "slide",
    weight: 700,
    italic: false,
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    font: "Inter, system-ui, sans-serif",
    color: "#e879f9",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(232,121,249,0.2)",
    letterSpacing: "0.05em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "vintage-film",
    name: "Vintage Film",
    font: "'Georgia', serif",
    color: "#fbbf24",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.6)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: true,
  },
  {
    id: "typewriter",
    name: "Typewriter",
    font: "'Courier New', monospace",
    color: "#e4e4e7",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.5)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "gradient-gold",
    name: "Gradient Gold",
    font: "Inter, system-ui, sans-serif",
    color: "#fbbf24",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.45)",
    shadow: "0 1px 6px rgba(0,0,0,0.3)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "midnight",
    name: "Midnight",
    font: "Inter, system-ui, sans-serif",
    color: "#94a3b8",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.5)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "tangerine",
    name: "Tangerine",
    font: "Inter, system-ui, sans-serif",
    color: "#fb923c",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(251,146,60,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "mint",
    name: "Mint",
    font: "Inter, system-ui, sans-serif",
    color: "#34d399",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(52,211,153,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "ruby",
    name: "Ruby Red",
    font: "Inter, system-ui, sans-serif",
    color: "#fb7185",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(251,113,133,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "sunset",
    name: "Sunset",
    font: "Inter, system-ui, sans-serif",
    color: "#fdba74",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.4)",
    shadow: "0 0 20px rgba(253,186,116,0.15)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    font: "Inter, system-ui, sans-serif",
    color: "#60a5fa",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(96,165,250,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "forest",
    name: "Forest Green",
    font: "Inter, system-ui, sans-serif",
    color: "#4ade80",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(74,222,128,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "royal",
    name: "Royal Purple",
    font: "Inter, system-ui, sans-serif",
    color: "#c084fc",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(192,132,252,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 800,
    italic: false,
  },
  {
    id: "crystal",
    name: "Crystal Clear",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(255,255,255,0.06)",
    shadow: "none",
    letterSpacing: "0.04em",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "paper",
    name: "Paper Cutout",
    font: "'Georgia', serif",
    color: "#292524",
    stroke: "transparent",
    bg: "#fef3c7",
    shadow: "0 1px 3px rgba(0,0,0,0.1)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 700,
    italic: false,
  },
  {
    id: "cinematic",
    name: "Cinematic",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.55)",
    shadow: "0 1px 4px rgba(0,0,0,0.2)",
    letterSpacing: "0.06em",
    case: "uppercase",
    animation: "fade",
    weight: 600,
    italic: false,
  },
];
