/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as LoginRouteImport } from './routes/login';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as IndexRouteImport } from './routes/index';
import { Route as EditorJobIdRouteImport } from './routes/editor.$jobId';
import { Route as PricingRouteImport } from './routes/pricing';
import { Route as AboutRouteImport } from './routes/about';
import { Route as ChangelogRouteImport } from './routes/changelog';
import { Route as PrivacyRouteImport } from './routes/privacy';
import { Route as TermsRouteImport } from './routes/terms';
import { Route as TemplatesRouteImport } from './routes/templates';
import { Route as PluginDownloadRouteImport } from './routes/plugin.download';
import { Route as CheckoutRouteImport } from './routes/checkout';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport
});
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport
});
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport
});
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
});
const EditorJobIdRoute = EditorJobIdRouteImport.update({
  id: '/editor/$jobId',
  path: '/editor/$jobId',
  getParentRoute: () => rootRouteImport
});
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport
});
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport
});
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport
});
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport
});
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport
});
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport
});
const PluginDownloadRoute = PluginDownloadRouteImport.update({
  id: '/plugin/download',
  path: '/plugin/download',
  getParentRoute: () => rootRouteImport
});
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport
});

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport
});

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EditorJobIdRoute: EditorJobIdRoute,
  PricingRoute: PricingRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TemplatesRoute: TemplatesRoute,
  PluginDownloadRoute: PluginDownloadRoute,
  CheckoutRoute: CheckoutRoute,
  AdminRoute: AdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
};

export const routeTree = rootRouteImport.
_addFileChildren(rootRouteChildren).
_addFileTypes();
